### ISSUE TITLE
SIP will not Disable with provided value.

### ISSUE THREAD

**Issue by bennydf123** [perez987/Broadcom-wifi-back-on-macOS-Sonoma-with-OCLP#1]
I've followed the instructions and when I go to OCLP it says I haven't disabled SIP when I have inputed the values correctly.

**Comment by perez987** [comment]
@bennydf123 
Show me your config.plist.

**Comment by perez987** [comment]
@bennydf123
Closing this for now. If you upload your config.plist or comment anything, I'll open it.
