### ISSUE TITLE
Sonoma 14.6 WiFi is disabled !!!

### ISSUE THREAD

**Issue by yangbe** [perez987/Broadcom-wifi-back-on-macOS-Sonoma-with-OCLP#4]
# WiFi Card info
**BCM94360CS2**

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/d3ca0167-7093-4dbb-9da3-db36724142b9"><br>

<img width="492" alt="image" src="https://github.com/user-attachments/assets/af58d9e7-6d42-442d-a5ca-313e833e024d">

# macOS Version
![image](https://github.com/user-attachments/assets/b9a941c7-bfda-48a9-98b5-9d0082f397ba)

**Comment by perez987** [comment]
@yangbe 
Please give to me more info:

- is it a Fenvi?
- Was Wi-Fi working prior to 14.6?
- OpenCore or Clover? Version?
- Are you following guidelines of the block [March 2024: macOS Sonoma 14.4 breaks OCLP root patch](https://github.com/perez987/Broadcom-wifi-back-on-macOS-Sonoma-with-OCLP#march-2024-macos-sonoma-144-breaks-oclp-root-patch)?
- Do you have OCLP 1.4.2 or newer?

Let me see your config.plist file.

**Comment by perez987** [comment]
Closing for now. It can be reopened if @yangbe posts anything more.
